-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.Character exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Character
selection constructor =
    Object.selection constructor
uid : Field String Api.Object.Character
uid =
      Object.fieldDecoder "uid" [] (Decode.string)


name : Field String Api.Object.Character
name =
      Object.fieldDecoder "name" [] (Decode.string)


gender : Field (Maybe String) Api.Object.Character
gender =
      Object.fieldDecoder "gender" [] (Decode.string |> Decode.nullable)


yearOfBirth : Field (Maybe String) Api.Object.Character
yearOfBirth =
      Object.fieldDecoder "yearOfBirth" [] (Decode.string |> Decode.nullable)


monthOfBirth : Field (Maybe String) Api.Object.Character
monthOfBirth =
      Object.fieldDecoder "monthOfBirth" [] (Decode.string |> Decode.nullable)


dayOfBirth : Field (Maybe String) Api.Object.Character
dayOfBirth =
      Object.fieldDecoder "dayOfBirth" [] (Decode.string |> Decode.nullable)


placeOfBirth : Field (Maybe String) Api.Object.Character
placeOfBirth =
      Object.fieldDecoder "placeOfBirth" [] (Decode.string |> Decode.nullable)


yearOfDeath : Field (Maybe String) Api.Object.Character
yearOfDeath =
      Object.fieldDecoder "yearOfDeath" [] (Decode.string |> Decode.nullable)


monthOfDeath : Field (Maybe String) Api.Object.Character
monthOfDeath =
      Object.fieldDecoder "monthOfDeath" [] (Decode.string |> Decode.nullable)


dayOfDeath : Field (Maybe String) Api.Object.Character
dayOfDeath =
      Object.fieldDecoder "dayOfDeath" [] (Decode.string |> Decode.nullable)


placeOfDeath : Field (Maybe String) Api.Object.Character
placeOfDeath =
      Object.fieldDecoder "placeOfDeath" [] (Decode.string |> Decode.nullable)


height : Field (Maybe String) Api.Object.Character
height =
      Object.fieldDecoder "height" [] (Decode.string |> Decode.nullable)


weight : Field (Maybe String) Api.Object.Character
weight =
      Object.fieldDecoder "weight" [] (Decode.string |> Decode.nullable)


deceased : Field (Maybe String) Api.Object.Character
deceased =
      Object.fieldDecoder "deceased" [] (Decode.string |> Decode.nullable)


bloodType : Field (Maybe String) Api.Object.Character
bloodType =
      Object.fieldDecoder "bloodType" [] (Decode.string |> Decode.nullable)


maritalStatus : Field (Maybe String) Api.Object.Character
maritalStatus =
      Object.fieldDecoder "maritalStatus" [] (Decode.string |> Decode.nullable)


serialNumber : Field (Maybe String) Api.Object.Character
serialNumber =
      Object.fieldDecoder "serialNumber" [] (Decode.string |> Decode.nullable)


hologramActivationDate : Field (Maybe String) Api.Object.Character
hologramActivationDate =
      Object.fieldDecoder "hologramActivationDate" [] (Decode.string |> Decode.nullable)


hologramStatus : Field (Maybe String) Api.Object.Character
hologramStatus =
      Object.fieldDecoder "hologramStatus" [] (Decode.string |> Decode.nullable)


hologramDateStatus : Field (Maybe String) Api.Object.Character
hologramDateStatus =
      Object.fieldDecoder "hologramDateStatus" [] (Decode.string |> Decode.nullable)


hologram : Field (Maybe Bool) Api.Object.Character
hologram =
      Object.fieldDecoder "hologram" [] (Decode.bool |> Decode.nullable)


fictionalCharacter : Field (Maybe Bool) Api.Object.Character
fictionalCharacter =
      Object.fieldDecoder "fictionalCharacter" [] (Decode.bool |> Decode.nullable)


mirror : Field (Maybe Bool) Api.Object.Character
mirror =
      Object.fieldDecoder "mirror" [] (Decode.bool |> Decode.nullable)


alternateReality : Field (Maybe Bool) Api.Object.Character
alternateReality =
      Object.fieldDecoder "alternateReality" [] (Decode.bool |> Decode.nullable)
